### ISSUE TITLE
What is the status

### ISSUE THREAD

**Issue by HNaga** [vishdha/transport_management_system#1]
What is the status of Transport management system?
I can not find it in App Installer
and error when tried to install manally

**Comment by vishdha** [comment]
what error you have received. please, can you provide traceback so that I can resolve?

**Comment by vishdha** [comment]
To install manually you need to follow this command
bench get-app https://github.com/vishdha/transport_management_system
bench create-site test_site
bench --site test_site install-app erpnext 
bench --site test_site install-app transport_managment_system
